version: "3"
services:

  # Postgres
  service-db:
    container_name: service-db
    image: postgres
    volumes:
      - service-db-data:/${PGDATA}
    env_file:
      - .env
    ports:
      - 5432:5432

  flyway:
    container_name: flyway
    image: flyway/flyway
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - .env

  # Service
  api-service:
    container_name: api-service
    build: .
    ports:
      - 5500:5500
      - 15500:15500
    env_file:
      - .env

volumes:
  service-db-data: